### ISSUE TITLE
Store: only last message/no message retrieved

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#882]
Performed today on test fleet, using latest master `chat2` locally:

```

src/status-im/nim-waku  master ✔                                                                                                             3d21h  ⍉
▶ ./build/chat2 --fleet=Test      
Choose a nickname >> franck
Welcome, franck!
Connecting to test fleet using DNS discovery...
Discovered and connecting to @[16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ, 16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm, 16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS]
Listening on
 /ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAmB6Mj19gWtN5ZHeKUfUvndQkLhcf4zjprhfBXFLTAKNQF
Store enabled, but no store nodes configured. Choosing one at random from discovered peers
Connecting to storenode: 16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ
<Feb 28, 18:16> winter bush: werf
<Feb 28, 18:17> winter bush: Heelo
<Mar 01, 18:18> wandering shadow: f
<Feb 25, 00:32> richard-Sx7PELbg: A
<Mar 01, 18:18> wandering shadow: asdf
<Mar 01, 18:18> wandering shadow: sdf
<Feb 25, 11:35> richard-ZNcVibwj: test
<Mar 01, 18:18> wandering shadow: adsf
<Mar 01, 18:18> wandering shadow: 
<Mar 01, 18:18> wandering shadow: adsf
<Mar 01, 18:18> wandering shadow: 
<Mar 01, 15:40> late sea: Has anyone here?
<Mar 01, 18:18> wandering shadow: asdf
<Mar 01, 18:18> wandering shadow: as
<Mar 01, 18:18> wandering shadow: fasdf
<Feb 28, 18:18> winter bush: sdsdsd
<Mar 01, 18:17> wandering shadow: asdfasdf
<Mar 01, 18:18> wandering shadow: asd
<Feb 28, 18:16> winter bush: dsfsdf
<Feb 28, 18:18> winter bush: dsfsdfsdfsd
<Mar 01, 18:18> wandering shadow: f
<Mar 01, 18:18> wandering shadow: df
<Mar 01, 18:18> wandering shadow: as
<Mar 01, 18:18> wandering shadow: asdfasdf
<Feb 25, 00:32> richard-Sx7PELbg: C
<Feb 25, 11:42> richard-3WEUaQgp: test
<Mar 01, 18:18> wandering shadow: df
<Mar 01, 18:18> wandering shadow: sdf
<Mar 01, 18:18> wandering shadow: ffasd
<Feb 28, 18:17> winter bush: ddd
<Feb 28, 18:17> winter bush: Hello
<Feb 28, 18:18> winter bush: so
<Feb 25, 11:42> richard-3WEUaQgp: test
<Feb 28, 18:17> winter bush: sdsd
<Mar 01, 18:18> wandering shadow: as
<Mar 01, 18:18> wandering shadow: asdfasd
<Mar 01, 18:17> wandering shadow: test
<Mar 01, 18:18> wandering shadow: df
<Mar 01, 18:18> wandering shadow: a
<Feb 28, 18:18> winter bush: OMG
<Mar 01, 18:18> wandering shadow: asd
<Mar 01, 18:18> wandering shadow: 
<Mar 01, 18:18> wandering shadow: f
<Feb 25, 00:32> richard-Sx7PELbg: B
<Mar 01, 18:18> wandering shadow: 
>> hello there
<Mar 07, 18:34> franck: hello there
>> what is going here?
<Mar 07, 18:34> franck: what is going here? ### MESSAGES SENT HERE
>> 1    
<Mar 07, 18:34> franck: 1
>> 2
<Mar 07, 18:34> franck: 2
>> 3
<Mar 07, 18:34> franck: 3
>> 4
<Mar 07, 18:34> franck: 4
>> ^CTraceback (most recent call last, using override)
/home/froyer/src/status-im/nim-waku/vendor/nim-eth/eth/common/eth_types.nim(982) main
/home/froyer/src/status-im/nim-waku/vendor/nim-eth/eth/common/eth_types.nim(975) NimMain
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(1091) waitFor
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(279) poll
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncfutures2.nim(368) futureContinue
/home/froyer/src/status-im/nim-waku/examples/v2/chat2.nim(538) processInput
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(1085) runForever
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(721) poll
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/ioselects/ioselectors_epoll.nim(379) selectInto
/home/froyer/src/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(610) signalHandler
SIGINT: Interrupted by Ctrl-C.

src/status-im/nim-waku  master ✔                                                                                                             3d21h  ⍉
▶ ./build/chat2 --fleet=Test
Choose a nickname >> franck
Welcome, franck!
Connecting to test fleet using DNS discovery...
Discovered and connecting to @[16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ, 16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm, 16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS]
Listening on
 /ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAm3H3nS1QiqSR11V7xYLAkhJd3ouRyr4ARNYYqHHN8daS5
Store enabled, but no store nodes configured. Choosing one at random from discovered peers
Connecting to storenode: 16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ
<Mar 07, 18:34> franck: 4
<Feb 28, 18:16> winter bush: werf
<Feb 28, 18:17> winter bush: Heelo
<Mar 01, 18:18> wandering shadow: f
<Feb 25, 00:32> richard-Sx7PELbg: A
<Mar 01, 18:18> wandering shadow: asdf
<Mar 01, 18:18> wandering shadow: sdf
<Feb 25, 11:35> richard-ZNcVibwj: test
<Mar 01, 18:18> wandering shadow: adsf
<Mar 01, 18:18> wandering shadow: 
<Mar 01, 18:18> wandering shadow: adsf
<Mar 01, 18:18> wandering shadow: 
<Mar 01, 15:40> late sea: Has anyone here?
<Mar 01, 18:18> wandering shadow: asdf
<Mar 01, 18:18> wandering shadow: as
<Mar 01, 18:18> wandering shadow: fasdf
<Feb 28, 18:18> winter bush: sdsdsd
<Mar 01, 18:17> wandering shadow: asdfasdf
<Mar 01, 18:18> wandering shadow: asd
<Feb 28, 18:16> winter bush: dsfsdf
<Feb 28, 18:18> winter bush: dsfsdfsdfsd
<Mar 01, 18:18> wandering shadow: f
<Mar 01, 18:18> wandering shadow: df
<Mar 01, 18:18> wandering shadow: as
<Mar 01, 18:18> wandering shadow: asdfasdf
<Feb 25, 00:32> richard-Sx7PELbg: C
<Feb 25, 11:42> richard-3WEUaQgp: test
<Mar 01, 18:18> wandering shadow: df
<Mar 01, 18:18> wandering shadow: sdf
<Mar 01, 18:18> wandering shadow: ffasd
<Feb 28, 18:17> winter bush: ddd
<Feb 28, 18:17> winter bush: Hello
<Feb 28, 18:18> winter bush: so
<Feb 25, 11:42> richard-3WEUaQgp: test
<Feb 28, 18:17> winter bush: sdsd
<Mar 01, 18:18> wandering shadow: as
<Mar 01, 18:18> wandering shadow: asdfasd
<Mar 01, 18:17> wandering shadow: test
<Mar 01, 18:18> wandering shadow: df
<Mar 01, 18:18> wandering shadow: a
<Feb 28, 18:18> winter bush: OMG
<Mar 01, 18:18> wandering shadow: asd
<Mar 01, 18:18> wandering shadow: 
<Mar 01, 18:18> wandering shadow: f
<Feb 25, 00:32> richard-Sx7PELbg: B
<Mar 01, 18:18> wandering shadow:  ### RELOADED, NO MESSAGE FROM FRANCK
>> sent from 0 - 241,230,197,23
>> sent from 2 - 241,230,197,23
>> sent from 1 - 241,230,197,23
>> sent from 0 - 76,94,24,97
>> sent from 2 - 76,94,24,97
>> sent from 1 - 76,94,24,97
>> sent from 0 - 20,191,16,82
>> sent from 2 - 20,191,16,82
>> sent from 1 - 20,191,16,82
>> ^CTraceback (most recent call last, using override)
/home/froyer/src/status-im/nim-waku/vendor/nim-eth/eth/common/eth_types.nim(982) main
/home/froyer/src/status-im/nim-waku/vendor/nim-eth/eth/common/eth_types.nim(975) NimMain
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(1091) waitFor
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(279) poll
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncfutures2.nim(368) futureContinue
/home/froyer/src/status-im/nim-waku/examples/v2/chat2.nim(538) processInput
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(1085) runForever
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(721) poll
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/ioselects/ioselectors_epoll.nim(379) selectInto
/home/froyer/src/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(610) signalHandler
SIGINT: Interrupted by Ctrl-C.

src/status-im/nim-waku  master ✔                                                                                                             3d21h  ⍉
▶ ./build/chat2 --fleet=Test
Choose a nickname >> fr
Welcome, fr!
Connecting to test fleet using DNS discovery...
Discovered and connecting to @[16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ, 16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm, 16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS]
Listening on
 /ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAmDZgGXFe1fFmfgiwb47hoL4VSh41eejTuTL3WrdKQYajW
Store enabled, but no store nodes configured. Choosing one at random from discovered peers
Connecting to storenode: 16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ
<Feb 28, 18:16> winter bush: werf
<Feb 28, 18:17> winter bush: Heelo
<Mar 01, 18:18> wandering shadow: f
<Feb 25, 00:32> richard-Sx7PELbg: A
<Mar 01, 18:18> wandering shadow: asdf
<Mar 01, 18:18> wandering shadow: sdf
<Feb 25, 11:35> richard-ZNcVibwj: test
<Mar 01, 18:18> wandering shadow: adsf
<Mar 01, 18:18> wandering shadow: 
<Mar 01, 18:18> wandering shadow: adsf
<Mar 01, 18:18> wandering shadow: 
<Mar 01, 15:40> late sea: Has anyone here?
<Mar 01, 18:18> wandering shadow: asdf
<Mar 01, 18:18> wandering shadow: as
<Mar 01, 18:18> wandering shadow: fasdf
<Feb 28, 18:18> winter bush: sdsdsd
<Mar 01, 18:17> wandering shadow: asdfasdf
<Mar 01, 18:18> wandering shadow: asd
<Feb 28, 18:16> winter bush: dsfsdf
<Feb 28, 18:18> winter bush: dsfsdfsdfsd
<Mar 01, 18:18> wandering shadow: f
<Mar 01, 18:18> wandering shadow: df
<Mar 01, 18:18> wandering shadow: as
<Mar 01, 18:18> wandering shadow: asdfasdf
<Feb 25, 00:32> richard-Sx7PELbg: C
<Feb 25, 11:42> richard-3WEUaQgp: test
<Mar 01, 18:18> wandering shadow: df
<Mar 01, 18:18> wandering shadow: sdf
<Mar 01, 18:18> wandering shadow: ffasd
<Feb 28, 18:17> winter bush: ddd
<Feb 28, 18:17> winter bush: Hello
<Feb 28, 18:18> winter bush: so
<Feb 25, 11:42> richard-3WEUaQgp: test
<Feb 28, 18:17> winter bush: sdsd
<Mar 01, 18:18> wandering shadow: as
<Mar 01, 18:18> wandering shadow: asdfasd
<Mar 01, 18:17> wandering shadow: test
<Mar 01, 18:18> wandering shadow: df
<Mar 01, 18:18> wandering shadow: a
<Feb 28, 18:18> winter bush: OMG
<Mar 01, 18:18> wandering shadow: asd
<Mar 01, 18:18> wandering shadow: 
<Mar 01, 18:18> wandering shadow: f
<Feb 25, 00:32> richard-Sx7PELbg: B
<Mar 01, 18:18> wandering shadow: ### LOADED AGAIN, NO MESSAGES FROM FRANCK
>> /home/froyer/src/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/threads.nim(165) threadProcWrapper
/home/froyer/src/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/threads.nim(156) threadProcWrapStackFrame
/home/froyer/src/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/threads.nim(141) threadProcWrapDispatch
/home/froyer/src/status-im/nim-waku/examples/v2/chat2.nim(342) readInput
/home/froyer/src/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/io.nim(365) readLine
/home/froyer/src/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/io.nim(141) raiseEOF
Error: unhandled exception: EOF reached [EOFError]
```

Please note similar behavior is observed when using js-waku against the test fleet. Only one message is retrieved. To reproduce:

```
// in js-waku repo
git fetch
git checkout test fleet
npm i
mocha ./src/lib/nwaku.spec.ts --grep "^Test nwaku test fleet Store$"
```
Result:

```
/dns4/node-01.ac-cn-hongkong-c.wakuv2.test.statusim.net/tcp/443/wss/p2p/16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm: ready
/dns4/node-01.gc-us-central1-a.wakuv2.test.statusim.net/tcp/443/wss/p2p/16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS: ready
/dns4/node-01.do-ams3.wakuv2.test.statusim.net/tcp/443/wss/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ: ready
0 [ 'sent from 1 - 76,94,24,97' ]

AssertionError: expected [ 'sent from 1 - 76,94,24,97' ] to include 'sent from 0 - 76,94,24,97'
    at /home/froyer/src/status-im/js-waku/src/lib/nwaku.spec.ts:157:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Context.<anonymous> (src/lib/nwaku.spec.ts:161:5)
```

The test is as follows:
1. 3 js-waku nodes are started, each connect to one test fleet node.\
2. Each waku node sends a message over relay with their index in `sent from 0` for first js-waku node.
3. We wait 1 second
4. Each js-waku node do a store query on their connected node

**Expected:** retrieve at least 3 messages: `["`sent from 1",  "sent from 2",  "sent from 3"]`.
**Actual**: only one message is ever retrieved.

**Comment by D4nte** [comment]
_Please note I started with the wrong assumptions, was testing against test fleet when I should have been testing 0.8 deployed on prod fleet_

## Notes from discussion Vac PM 7 MAR EU/AS

- New bug seems to be a logic bug as only latest message is returned.

Plan:
1. @D4nte to test against **prod** fleet to confirm whether this bug is present and performance is resolved in v0.8.
2. staheri14 to investigate and attempt to fix the issue
3. Contingency plan 1: Fix the bug
4. Contingency plan 2: Deploy v0.7 and do DB reset. Preferably **not** in prod fleet: either test fleet or waku connect fleet (but waku connect fleet would need websockify deployed).

**Comment by oskarth** [comment]
^ @jm-clius for when you back on Wednesday assuming not resolved by then

**Comment by D4nte** [comment]
More investigation needed but there seems to be an issue with the prod fleet which I was not able to reproduce with local nim-waku v0.8 instance:
- Running js-waku test suite with nim-waku v0.8 works fine. Test `Retrieves history using callback` confirms that 20 messages sent to the nwaku node via relay are retrieved via store (page size 10)
- https://js-waku.wakuconnect.dev/examples/web-chat/ stills returns 0 or 1 messages (connected to prod fleet)
- nim-waku's `/chat2 --fleet=Prod` retrieves messages but last message is always `<Mar 03, 01:11> dry waterfall: don't see hello world` despite sending new message with it.

**Comment by jm-clius** [comment]
I think this is related to current store DB, perhaps invalid or corrupt timestamps:
https://github.com/status-im/nim-waku/pull/878 is especially important, and
https://github.com/status-im/nim-waku/pull/876 could play a role as well.

**Comment by jm-clius** [comment]
Right so far in investigation:
1. Some messages already stored on `test` had dodgy timestamps way in the future. This caused them to always be returned at the head of backward-paged historical queries and all new messages to be sorted "behind" them. This was solved by simply wiping those DBs and historical queries on both wakuv2.test and status.test fleets now return clean responses. This PR is already aimed at preventing dodgy timestamps from being stored: https://github.com/status-im/nim-waku/pull/876
2. A bug in nanotimestamp conversion may cause the `nwaku` version of `chat2` to use timestamps way in the past. although https://github.com/status-im/nim-waku/pull/877 is also required for `chat2` messages to have their timestamp set at all. This only affected the toy-chat application (not the `store`), but can cause new `chat2` messages _from the nim-waku client_ to be sorted at the very back of the `store` queue (and then likely removed as the `store` removes oldest messages when at capacity). A fix for this has already been merged here: https://github.com/status-im/nim-waku/pull/878

So far other tests seem to pass without issue.

**Comment by jm-clius** [comment]
I've also confirmed that the version of `chat2` with the fixes above (i.e. built off this branch: https://github.com/status-im/nim-waku/pull/877) works as expected when connecting to `prod` and `test` fleets.

**Comment by D4nte** [comment]
@jm-clius I am not sure the issue I reported is covered by the investigation.

When doing some test today, I sent a message and then do a store query against the prod fleet with the following timestamps:

```
1646783920581000 # message's timestamp
1646179229860000 # start time
1646784029860000 # end time
```

This looks correct to me. The message's timestamp is indeed between the start and end times.

However, no result are returned by the query.

**Comment by D4nte** [comment]
@jm-clius I just tried with #877 and the store query does not return any messages:

```

src/status-im/nim-waku  feat/chat2-improve ✔                                                                                                                                                                                            1d3h  
▶ make update ; make chat2
Building: install/usr/lib/libbacktracenim.a
Building: build/chat2
[NimScript] exec: nim c --out:build/chat2 -d:chronicles_log_level=DEBUG -d:chronicles_sinks=textlines[file] -d:ssl --verbosity:0 --hints:off -d:release -d:discv5_protocol_id:d5waku examples/v2/chat2.nim
/home/froyer/src/status-im/nim-waku/waku/v2/protocol/waku_relay.nim(60, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
/home/froyer/src/status-im/nim-waku/waku/v2/protocol/waku_relay.nim(75, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
/home/froyer/src/status-im/nim-waku/waku/v2/protocol/waku_relay.nim(81, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
/home/froyer/src/status-im/nim-waku/waku/v2/protocol/waku_store/waku_store.nim(10, 6) Warning: imported and not used: 'algorithm' [UnusedImport]
/home/froyer/src/status-im/nim-waku/waku/v2/utils/wakuswitch.nim(6, 7) Warning: imported and not used: 'byteutils' [UnusedImport]
/home/froyer/src/status-im/nim-waku/waku/v2/utils/wakuswitch.nim(4, 6) Warning: imported and not used: 'sequtils' [UnusedImport]
/home/froyer/src/status-im/nim-waku/waku/v2/utils/wakuswitch.nim(10, 23) Warning: imported and not used: 'dnsresolver' [UnusedImport]
/home/froyer/src/status-im/nim-waku/waku/v2/node/discv5/waku_discv5.nim(4, 6) Warning: imported and not used: 'sequtils' [UnusedImport]
/home/froyer/src/status-im/nim-waku/waku/v2/node/discv5/waku_discv5.nim(9, 3) Warning: imported and not used: 'config' [UnusedImport]
/home/froyer/src/status-im/nim-waku/waku/v2/node/wakunode2.nim(23, 22) Warning: imported and not used: 'migration_types' [UnusedImport]
/home/froyer/src/status-im/nim-waku/examples/v2/chat2.nim(346, 63) template/generic instantiation of `async` from here
/home/froyer/src/status-im/nim-waku/examples/v2/chat2.nim(350, 21) template/generic instantiation of `load` from here
/home/froyer/src/status-im/nim-waku/vendor/nim-confutils/confutils.nim(849, 23) Warning: Cannot prove that 'result' is initialized. This will become a compile time error in the future. [ProveInit]
/home/froyer/src/status-im/nim-waku/examples/v2/chat2.nim(9, 11) Warning: imported and not used: 'random' [UnusedImport]
/home/froyer/src/status-im/nim-waku/examples/v2/chat2.nim(9, 11) Warning: imported and not used: 'httpclient' [UnusedImport]
/home/froyer/src/status-im/nim-waku/examples/v2/chat2.nim(9, 11) Warning: imported and not used: 'sequtils' [UnusedImport]

src/status-im/nim-waku  feat/chat2-improve ✔                                                                                                                                                                                            1d3h  
▶ ./build/chat2 --fleet=Prod
Choose a nickname >> Franck
Welcome, Franck!
Connecting to prod fleet using DNS discovery...
Discovered and connecting to @[16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e, 16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD, 16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA]
Listening on
 /ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAm96L1CU4BsMLSkNP8hbHb67SGd9sdqWtJeKZCvHeTpqds
Store enabled, but no store nodes configured. Choosing one at random from discovered peers
Connecting to storenode: 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e
>> Hello there from nchat2.     
<Mar 09, 11:30> Franck: Hello there from nchat2.
>> Let's see if we receive any message
<Mar 09, 11:30> Franck: Let's see if we receive any message
>> <Mar 09, 11:31> franck: and what about here
>> Ok so we receive messages both sides, interesting
<Mar 09, 11:31> Franck: Ok so we receive messages both sides, interesting
>> Did receive an odd timestmamp at some point
<Mar 09, 11:31> Franck: Did receive an odd timestmamp at some point
>> ah, unrelated message timestamp, ok
<Mar 09, 11:32> Franck: ah, unrelated message timestamp, ok
>> ^CTraceback (most recent call last, using override)
/home/froyer/src/status-im/nim-waku/vendor/nim-eth/eth/common/eth_types.nim(982) main
/home/froyer/src/status-im/nim-waku/vendor/nim-eth/eth/common/eth_types.nim(975) NimMain
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(1091) waitFor
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(279) poll
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncfutures2.nim(368) futureContinue
/home/froyer/src/status-im/nim-waku/examples/v2/chat2.nim(539) processInput
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(1085) runForever
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/asyncloop.nim(721) poll
/home/froyer/src/status-im/nim-waku/vendor/nim-chronos/chronos/ioselects/ioselectors_epoll.nim(379) selectInto
/home/froyer/src/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(610) signalHandler
SIGINT: Interrupted by Ctrl-C.

src/status-im/nim-waku  feat/chat2-improve ✔                                                                                                                                                                                           1d3h  ⍉
▶ ./build/chat2 --fleet=Prod
Choose a nickname >> franck-nchat2 
Welcome, franck-nchat2!
Connecting to prod fleet using DNS discovery...
Discovered and connecting to @[16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e, 16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD, 16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA]
Listening on
 /ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAmR3EeqsaxkqYrVpbDrJmuEHT2SEuueYXVi3MGmuacb2zC
Store enabled, but no store nodes configured. Choosing one at random from discovered peers
Connecting to storenode: 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e
>> 
```

**Comment by D4nte** [comment]
Same behaviour when using https://github.com/status-im/nim-waku/pull/878

**Comment by D4nte** [comment]
ok, the issue is fixed on the **test** fleet. Does it mean we need to get https://github.com/status-im/nim-waku/pull/878 released?

**Comment by jm-clius** [comment]
Update on this issue: I've been testing a fix on the `prod` fleet for a couple of days and so far it's working well. I'll clean this up and have it merged and released asap.
